site_name: NSW Custom Game Icons
extra_css:
  - stylesheets/extra.css
  - stylesheets/hint.min.css
extra_javascript: [js/color_blocks.js]
repo_url: https://github.com/sodasoba1/NSW-Custom-Game-Icons/
theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: purple
  logo: img/logo.png

markdown_extensions:
    - admonition
    - toc: # https://python-markdown.github.io/extensions/toc/
          permalink: True
          toc_depth: 4
    - md_in_html
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.critic
    - pymdownx.superfences
    - pymdownx.keys
    - pymdownx.details
plugins:
  - tooltips
nav:
   - Home: 'index.md'
   - Before You Start:
                  - Prerequisites: 'pre.md'
                  - Sys-Tweak: 'sys-tweak.md'
                  - Sys-ftpd-light: 'sys-ftpd-light.md'
                  - SteamGridDB API: 'sg-api.md'
   - Themes:
                  - Supported Themes for Vertical & Horizontal: 'supportedthemes.md'
                  - Installing A Theme: 'installingtheme.md'
   - NX-GIC:
                  - NX-GIC: 'usingnxgic.md'
                  - Offline NX-GIC: 'offlinenxgic.md'
                  - Add New Via URL: 'add-new.md'
                  - Add New Via SteamGridDB: 'add-new-sg.md'
                  - Add New Via Browse: 'add-new-br.md'
                  - TroubleShooting: 'tblsht.md'
   - extra:
                  - Icon Search: 'icon.md'
                  - How to make your own icons: 'diy.md'
                  - Thanks & Credits: 'thanks.md'
                  - 14.0 Theme Fix: 'https://sodasoba1.github.io/FlaunchFix/'